# Generated by Django 5.0.6 on 2024-05-20 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={},
        ),
        migrations.RemoveField(
            model_name='libro',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='libro',
            name='persona_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto_web.persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='dni',
            field=models.IntegerField(default=0, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=255, verbose_name='Autor'),
        ),
        migrations.AlterModelTable(
            name='libro',
            table=None,
        ),
    ]
